version: "3.1"
services:
  backend-server:
    build: .
    container_name: backend_container
    command: node /myapp/backend/server.js 
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    depends_on:
      - mongodb_container
  client-server: 
    build: .
    container_name: client_container
    command: npm start /myapp/client
    ports:
      - 3000:3000
    environment:
      - PORT=3000

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
